### ISSUE TITLE
To maintain list items positions on device rotation

### ISSUE THREAD

**Issue by notnotnithin** [djkovrik/BakingApp#1]
In RecipeListFragment.java there is a need to implement the onSaveInstanceState and onActivityCreated methods to preserve and restore user or app state. We need to retain & restore the RecyclerView scroll position.
[RecipeListFragment.zip](https://github.com/djkovrik/BakingApp/files/1120995/RecipeListFragment.zip)

**Comment by djkovrik** [comment]
Hello and thanks for suggestion!
State saving didn't work for me for some reason so I made it with saving/restoring current scrolling position int.
